@startuml
project start 1 march of 2022
saturday are closed
sunday are closed
[Prototype design] lasts 30 days
[Test prototype] lasts 10 days
[K] starts 2022-03-01 and ends 2022-03-05
then [K2] ends 2022-03-12 





[K2] is colored in GreenYellow/Green
[Milestone esempio] happens at 2022-03-10
-- Vita Bucolica Web App -- 
[1] on {AL:100%}{LV:100%} lasts 2 days
then [2] on {AL:100%}{LV:100%} lasts 2 days
then [3] on {AL:100%}{LV:100%}{MR:100%} lasts 2 days
[4] on {AL:100%}{MR:100%} starts at [3]'s end and lasts 2 days
[5] on {LV:100%}{MR:100%} starts at [4]'s end and lasts 1 days
[6] on {GR:100%}{AB:100%} starts at [4]'s end and lasts 2 days
[G1] on {AL:100%}{AB:100%} starts at [6]'s end and lasts 1 days
[G2] on {AL:100%}{AB:100%}{GR:100%} starts at [G1]'s end and lasts 1 days
[7] on {LC:100%}{MG:100%} starts at [6]'s end and lasts 2 days
[8] on {LC:100%} starts at [7]'s end and lasts 1 days
[9] on {GR:100%}{LC:100%} starts at [G2]'s end and lasts 2 days
[T1] on {AL:100%}{LC:100%}{GR:100%}  starts at [9]'s end and lasts 1 days
[10] on {LC:100%}{MG:100%} starts at [T1]'s end and lasts 1 days
[11] on {MG:100%} starts at [10]'s end and lasts 1 days
[12] on {LC:100%}{MG:100%} starts at [11]'s end and lasts 2 days
[13] on {LV:100%}{MR:100%} starts at [12]'s end and lasts 3 days
[14] on {MG:100%} starts at [12]'s end and lasts 1 days
[15] on {MG:100%} starts at [14]'s end and lasts 3 days
[16] on {GR:100%}{LC:100%} starts at [13]'s end and lasts 1 days
[17] on {LC:100%}{GR:100%}{MG:100%} starts at [16]'s end and lasts 4 days
[18] on {LC:100%} starts at [17]'s end and lasts 2 days
[S1] on {AL:100%}{GR:100%} starts at [T1]'s end and lasts 1 days
[S2] on {GR:100%} starts at [S1]'s end and lasts 2 days
[T2] on {AL:100%}{LV:100%}{GR:100%}{MG:100%} starts at [18]'s end and lasts 3 days
[T3] on {AL:100%}{LV:100%} starts at [T2]'s end and lasts 1 days
[R] on {LV:100%}{GR:100%} starts at [T3]'s end and lasts 1 days

'hide ressources footbox
@enduml