	
@startwbs
skinparam roundCorner 20
<style>
wbsDiagram {
   LineColor lightgrey
   arrow{
    lineColor black
   }
   .powderBlue{
      backgroundColor midnightBlue
      fontColor white
   }
   .white{
      backgroundColor white
   }
   .orange{
      backgroundColor orange
   }
   .turquoise{
      backgroundColor paleturquoise
   }
   .violet{
      backgroundColor PaleVioletRed
   }
   .green{
      backgroundColor GreenYellow
   }
   
}
</style>
* Vita Bucolica Web Application <<powderBlue>>
** [1] Kick Off Progetto <<green>>
-** [2] Pianificazione <<green>>
-** [3] Analisi dei requisiti <<green>>
** [4] Documentazione architetturale <<orange>>
-** [5] Modellazione del dominio <<orange>>
-** [6] Mockup interfaccia applicazione <<orange>>
*** [T1] Test di sistema release anticipata <<orange>>
-** [T2] Test di sistema finale <<orange>>
-** [T3] Test pilota <<orange>>

** All User Services
*** Iscrizione al sito 
**** Login/Logout al sito 
***** [7] Autenticazione Utuenti Pagina <<orange>>
*** Ricerca articoli Tag & Parola Chiave
**** [15] Implementazione funzione di ricerca mediante Tag <<orange>>
**** [16] Implementazione funzione di ricerca mediante Form <<orange>>
*** CRUD commenti
**** [17] Implementazione CRUD commenti <<orange>>
*** Visualizza Prodotti Boutique Contadina
**** [11] Implementazione pagina visualizzazione listino prezzi <<orange>>
**** Ordina Prodotti Boutique Condadina
***** [12] Implementazione pagina ordini <<orange>>
** Expert User Services
*** CRUD Articolo
**** [13] Implementazione pagina CRUD articoli <<orange>> 
** Administrator Command Console 
*** Login privilegiato/Logout
**** [8] Autenticazione Amministratore <<orange>>
*** CRUD Moderazione Articoli
**** [14] Implementazione funzioni di moderazione articoli <<orange>>
*** CRUD Moderazione Commenti
**** [18] Implementazione funzioni di moderazione commenti <<orange>>
*** Inserimento listino prezzi
**** [9] Implementazione pagina inserimento prezzi<<orange>>
*** Ricevi/Visualizza/Conferma Ordini Boutique Contadina
**** [10] Implementazione pagina ricezione ordini<<orange>>
** [G1] Briefing Grafico <<turquoise>>
-** [G2] Scelta Proposte <<turquoise>>
** [S1] Briefing SEO expert <<violet>>
-** [S2] SEO strategy application <<violet>>
@endwbs