@startuml CCC

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/material/nfc.puml

left to right direction
skinparam actorStyle awesome
skinparam actor {
BorderColor DarkRed
}

skinparam usecase {
BackgroundColor LightGoldenRodYellow
BorderColor DarkRed
ArrowColor DarkRed

}

!define SHADOW_COLOR #000000
skinparam {
  Shadowing true
  ShadowColor SHADOW_COLOR
}

actor Paziente as Utente 
cloud cloud #FF9900;line:black;line.bold;text:black [
AWS Cloud
]
rectangle "Mobile App" {
    MATERIAL_NFC(nfc,Lettura e Scrittura NFC)
	(Iscrizione) as iscrizione
	(Ingresso) as ingresso
	(Seleziona / Visualizza Condizione/i) as condizione
	(Carica / Ricerca / Scarica Documenti) as azioni
	(Concedi / Rimuovi Permesso) as permesso

	
    azioni --> permesso
    nfc --> cloud
    azioni <--> cloud
    permesso --> cloud
	Utente --> iscrizione
    Utente --> ingresso
    Utente --> condizione
    condizione --> nfc
    Utente <--> azioni
}
@enduml